name: Deploy to FTP
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy with FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.2
        with:
         ftp-server: ftpupload.net
         ftp-username: ${{ secrets.FTP_USERNAME }}
         ftp-password: ${{ secrets.FTP_PASSWORD }}
         server-dir: /htdocs/

