name: Deploy to FTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy with FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
         ftp-server: ftpupload.net
         ftp-username: b7_34125153
         ftp-password: camilo97
       

